/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ilib;
import javax.swing.ImageIcon;

import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMaterialLighterIJTheme;
import com.mycompany.ilib.Dashboard;
import java.awt.Color;
import javax.swing.JOptionPane;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMaterialLighterIJTheme;
import java.sql.PreparedStatement;
import com.mycompany.db.Database.*;
//import static com.sun.tools.javac.tree.TreeInfo.args;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JFrame;
import java.net.URL;

/**
 *
 * @author scano
 */
public class Login extends javax.swing.JFrame {
    //    String usuarioG = "admin";
//    String passG = "123456";
    
    private char defaultEchoChar;
    private ImageIcon iconVisible;
    private ImageIcon iconInvisible;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        defaultEchoChar = passwordTxt.getEchoChar();

        // Cargar iconos de forma segura
        iconVisible = loadIcon("/visible.png");
        iconInvisible = loadIcon("/invisible.png");
        if (iconInvisible != null) hidden.setIcon(iconInvisible);

        InitStyles();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
//    
    
    private void InitStyles(){
        userLblTxt.putClientProperty( "FlatLaf.style", "font: bold $h3.regular.font" );
        userLblTxt.setForeground(Color.black);
   
        passwordLblTxt.putClientProperty( "FlatLaf.style", "font: bold $h3.regular.font" );
        passwordLblTxt.setForeground(Color.black);
        
        
        loginButtonTxt.putClientProperty( "FlatLaf.style", "font: bold $h3.regular.font" );
        loginButtonTxt.setForeground(Color.black);
        
        loginButtonTxt.putClientProperty("FlatLaf.style","font: bold $h3.regular.font");
        loginButtonTxt.setForeground(Color.white);
        
        titleTxt.putClientProperty("FlatLaf.style","font: bold $h1.regular.font");
        titleTxt.setForeground(Color.black);
        }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        passwordLblTxt = new javax.swing.JLabel();
        userLblTxt = new javax.swing.JLabel();
        userTxt = new javax.swing.JTextField();
        loginButtonTxt = new javax.swing.JButton();
        passwordTxt = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        hidden = new javax.swing.JLabel();
        titleTxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        passwordLblTxt.setText("Contraseña");

        userLblTxt.setText("usuario");

        userTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTxtActionPerformed(evt);
            }
        });

        loginButtonTxt.setBackground(new java.awt.Color(18, 90, 173));
        loginButtonTxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        loginButtonTxt.setForeground(new java.awt.Color(255, 255, 255));
        loginButtonTxt.setText("Iniciar");
        loginButtonTxt.setBorder(null);
        loginButtonTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonTxtActionPerformed(evt);
            }
        });

        passwordTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTxtActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/security.png"))); // NOI18N

        hidden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/invisible.png"))); // NOI18N
        hidden.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hiddenMouseClicked(evt);
            }
        });

        titleTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        titleTxt.setText("Login");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userTxt)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(passwordLblTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(userLblTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(titleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(passwordTxt)))
                .addGap(18, 18, 18)
                .addComponent(hidden)
                .addGap(81, 81, 81))
            .addGroup(layout.createSequentialGroup()
                .addGap(309, 309, 309)
                .addComponent(loginButtonTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                .addGap(344, 344, 344))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(titleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(userLblTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(passwordLblTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passwordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(hidden))
                .addGap(64, 64, 64)
                .addComponent(loginButtonTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        passwordTxt.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTxtActionPerformed

    private void loginButtonTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonTxtActionPerformed

        String username = "";
        String password = "";
        
        
        username = userTxt.getText();
        password = passwordTxt.getText();
        
        
        if(username.equals("") || password.equals("")){
                JOptionPane.showMessageDialog(null, "Ingrese el usuario y la contraseña");
        }else{

                if (checkCredentials(username, password)) {
                    JOptionPane.showMessageDialog(null, "Bienvenido");

                    cerrarVentana(this);
                    com.mycompany.ilib.Dashboard.main();
                    
                
                }else {
       
                    JOptionPane.showMessageDialog(null, "Usuario no encontrado");    
                }
        
            
        }
        
        
    }//GEN-LAST:event_loginButtonTxtActionPerformed

    private void passwordTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTxtActionPerformed

    private void hiddenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hiddenMouseClicked
        if (passwordTxt.getEchoChar() != 0) {
            passwordTxt.setEchoChar((char) 0); // mostrar
            if (iconVisible != null) hidden.setIcon(iconVisible);
        } else {
            passwordTxt.setEchoChar(defaultEchoChar); // ocultar
            if (iconInvisible != null) hidden.setIcon(iconInvisible);
        }
        hidden.revalidate();
        hidden.repaint();
    }//GEN-LAST:event_hiddenMouseClicked

    // Helper para cargar recursos y avisar si faltan
    private ImageIcon loadIcon(String path) {
        URL url = getClass().getResource(path);
        if (url == null) {
            System.err.println("No se encontró el recurso: " + path);
            return null;
        }
        return new ImageIcon(url);
    }
    
  
    
    
    private void cerrarVentana(JFrame frame){
        frame.dispose();
    }
    
    private static boolean checkCredentials(String username, String password) {
    com.mycompany.db.Database db = new com.mycompany.db.Database();
    return db.checkCredentials(username, password);
}
    
    
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {  
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
            FlatMaterialLighterIJTheme.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
                
            }
        });
        
        
       
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel hidden;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton loginButtonTxt;
    private javax.swing.JLabel passwordLblTxt;
    private static javax.swing.JPasswordField passwordTxt;
    private javax.swing.JLabel titleTxt;
    private javax.swing.JLabel userLblTxt;
    private static javax.swing.JTextField userTxt;
    // End of variables declaration//GEN-END:variables
}
