/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.views;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author stuart
 */
public class lent extends javax.swing.JPanel {

    /**
     * Creates new form lent
     */
    public lent() {
        initComponents();
    }

//    public void call(){
//        String query = "";
//        if(userToggle.isSelected()){
//            query = "SELECT  B.title as name,COUNT(B.title) as count FROM lendings AS l JOIN books AS b ON l.book_id = b.id JOIN users AS u ON l.user_id = u.id group by u.name;";
//        }else if(bookToggle.isSelected()){
//            query = "SELECT u.name as xd1, count(u.name) as xd2 FROM lendings AS l JOIN books AS b ON l.book_id = b.id JOIN users AS u ON l.user_id = u.id group by u.name;";
//        }
//        
//        loadTable(query);
//    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        userToggle = new javax.swing.JRadioButton();
        bookToggle = new javax.swing.JRadioButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre", "Prestado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnGroup.add(userToggle);
        userToggle.setText("usuario");
        userToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userToggleActionPerformed(evt);
            }
        });

        btnGroup.add(bookToggle);
        bookToggle.setText("libros");
        bookToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookToggleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 807, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(userToggle)
                .addGap(36, 36, 36)
                .addComponent(bookToggle)
                .addGap(53, 53, 53))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookToggle)
                    .addComponent(userToggle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public void loadTable(String query){
     
//        String query = "SELECT  B.title as name,COUNT(B.title) as count FROM lendings AS l JOIN books AS b ON l.book_id = b.id JOIN users AS u ON l.user_id = u.id group by u.name;";
        
         try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/ilib", "root", "");
                
                
                 
                Statement stmt = conn.createStatement();
                ResultSet rs = stmt.executeQuery(query)) {

                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.setRowCount(0); // Clear existing rows

                while (rs.next()) {
                    String nombre = rs.getString("name");
                    String prestado = rs.getString("count");
                    
                    model.addRow(new Object[]{nombre, prestado});
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
    }
    
    
    private void bookToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookToggleActionPerformed
        // TODO add your handling code here:
        
        String query = "";
        if(bookToggle.isSelected()){
        query = "SELECT  B.title as name,COUNT(B.title) as count FROM lendings AS l JOIN books AS b ON l.book_id = b.id JOIN users AS u ON l.user_id = u.id group by u.name;";

        }
        
        loadTable(query);
       
    }//GEN-LAST:event_bookToggleActionPerformed

    private void userToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userToggleActionPerformed
        // TODO add your handling code here:
      
        String query = "";
        if(userToggle.isSelected()){
        query = "SELECT u.name as name, count(u.name) as count FROM lendings AS l JOIN books AS b ON l.book_id = b.id JOIN users AS u ON l.user_id = u.id group by u.name;";
        }
        
        loadTable(query);
    }//GEN-LAST:event_userToggleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton bookToggle;
    private javax.swing.ButtonGroup btnGroup;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton userToggle;
    // End of variables declaration//GEN-END:variables
}
