/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.views;

import com.mycompany.ilib.DAOBooksImpl;
import com.mycompany.interfaces.DAOBooks;
import com.mycompany.utils.Utils;
import java.awt.Color;

/**
 *
 * @author stuart
 */
public class UpBooks extends javax.swing.JPanel {

    boolean isEdition = false;
    com.mycompany.models.Books bookEdition;
    /**
     * Creates new form Principal
     */
    public UpBooks() {
        initComponents();
        InitStyles();
    }
    
     public UpBooks(com.mycompany.models.Books book) {
        initComponents();
        isEdition = true;
        bookEdition = book;
        InitStyles();
    }
    
    private void InitStyles(){
        title.putClientProperty("FlatLaf.styleClass", "h1");
        title.setForeground(Color.black);
        isbnTxt.putClientProperty("JTextField.placeholderText", "Ingrese el isbn del libro");
        titleTxt.putClientProperty("JTextField.placeholderText", "Ingrese el título del libro");
        dateTxt.putClientProperty("JTextField.placeholderText", "Ingrese la de publicación del libro.");
        authorTxt.putClientProperty("JTextField.placeholderText", "Ingrese el autor del libro.");
        catTxt.putClientProperty("JTextField.placeholderText", "Ingrese la categoría del libro.");
        edTxt.putClientProperty("JTextField.placeholderText", "Ingrese la editorial del libro.");
        langTxt.putClientProperty("JTextField.placeholderText", "Ingrese el idioma del libro.");
        pagsTxt.putClientProperty("JTextField.placeholderText", "Ingrese las páginas totales del libro.");
        descTxt.putClientProperty("JTextField.placeholderText", "Ingrese la descripción del libro.");
        dispTxt.putClientProperty("JTextField.placeholderText", "Ingrese el número de libros disponibles.");

        if (isEdition) {
            title.setText("Editar Libro");
            button.setText("Guardar");

            if (bookEdition != null) {
                isbnTxt.setText(bookEdition.getId());
                titleTxt.setText(bookEdition.getTitle());
                dateTxt.setText(bookEdition.getDate());
                authorTxt.setText(bookEdition.getAuthor());
                catTxt.setText(bookEdition.getCategory());
                edTxt.setText(bookEdition.getEdit());
                langTxt.setText(bookEdition.getLang());
                pagsTxt.setText(bookEdition.getPages());
                descTxt.setText(bookEdition.getDescription());
                dispTxt.setText(bookEdition.getAvailable() + "");
//                ejemTxt.setText(bookEdition.getEjemplares());
            }
        }
      
        }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        pagsTxt = new javax.swing.JTextField();
        titleLbl = new javax.swing.JLabel();
        dispLbl = new javax.swing.JLabel();
        authorLbl = new javax.swing.JLabel();
        catLbl = new javax.swing.JLabel();
        edLbl = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        titleTxt = new javax.swing.JTextField();
        dateTxt = new javax.swing.JTextField();
        dispTxt = new javax.swing.JTextField();
        langTxt = new javax.swing.JTextField();
        button = new javax.swing.JButton();
        authorTxt = new javax.swing.JTextField();
        catTxt = new javax.swing.JTextField();
        edTxt = new javax.swing.JTextField();
        descTxt = new javax.swing.JTextField();
        pagsLbl = new javax.swing.JLabel();
        dateLbl = new javax.swing.JLabel();
        langLbl = new javax.swing.JLabel();
        descLbl = new javax.swing.JLabel();
        isbnTxt = new javax.swing.JTextField();
        titleLbl1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        setPreferredSize(new java.awt.Dimension(710, 380));

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setPreferredSize(new java.awt.Dimension(710, 380));

        pagsTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagsTxtActionPerformed(evt);
            }
        });

        titleLbl.setText("ISBN");

        dispLbl.setText("Disponibles");

        authorLbl.setText("Autor");

        catLbl.setText("Categoría");

        edLbl.setText("Edición");

        title.setText("Subir nuevo Libro");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        button.setBackground(new java.awt.Color(18, 90, 173));
        button.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        button.setText("Subir");
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });

        pagsLbl.setText("Páginas");

        dateLbl.setText("Fecha de Publicación");

        langLbl.setText("Idioma");

        descLbl.setText("Descripción");

        titleLbl1.setText("Título");

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(jSeparator2)
                        .addGap(34, 34, 34))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(edTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                            .addComponent(authorLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(titleLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(titleTxt)
                            .addComponent(dateTxt)
                            .addComponent(isbnTxt)
                            .addComponent(authorTxt)
                            .addComponent(catLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(catTxt)
                            .addComponent(edLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(83, 83, 83)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dispTxt)
                            .addComponent(descTxt)
                            .addComponent(pagsTxt)
                            .addComponent(langTxt)
                            .addComponent(pagsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(langLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(descLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dispLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33))))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(isbnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(titleLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(titleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(authorLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(authorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(catLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(catTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(edLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(langLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(langTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pagsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pagsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(descLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(descTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dispLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dispTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(button, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pagsTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagsTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pagsTxtActionPerformed

    private void buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActionPerformed
        // TODO add your handling code here:
        String isbn = isbnTxt.getText();
        String mtitle = titleTxt.getText();
        String rawDate = dateTxt.getText().trim();
        String author = authorTxt.getText();
        String cat = catTxt.getText();
        String ed = edTxt.getText();
        String lang = langTxt.getText();
        String pags = pagsTxt.getText();
        String desc = descTxt.getText();
        String disp = dispTxt.getText();

        // Validaciones para los campos
        if (isbn.isEmpty() || mtitle.isEmpty() || rawDate.isEmpty() || author.isEmpty() || cat.isEmpty() || ed.isEmpty()
                || lang.isEmpty() || pags.isEmpty() || desc.isEmpty() || disp.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe llenar todos los campos. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            titleTxt.requestFocus();
            return;
        } else if (!Utils.isNumeric(disp)) {
            javax.swing.JOptionPane.showMessageDialog(this, "El campo Disponibles debe ser un número entero. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            dispTxt.requestFocus();
            return;
        } else if (!Utils.isNumeric(author) || !Utils.isNumeric(cat) || !Utils.isNumeric(ed) || !Utils.isNumeric(lang)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Author, Category, Publisher y Language deben ser IDs numéricos.", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        String mysqlDate;
        try {
            mysqlDate = Utils.parseDateToMysql(rawDate);
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Fecha inválida: " + ex.getMessage(), "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            dateTxt.requestFocus();
            return;
        }

        com.mycompany.models.Books book = isEdition ? bookEdition : new com.mycompany.models.Books();
        book.setId(isbn);
        book.setTitle(mtitle);
        book.setDate(mysqlDate);
        book.setAuthorId(Integer.parseInt(author));
        book.setCategoryId(Integer.parseInt(cat));
        book.setPublisherId(Integer.parseInt(ed));
        book.setLanguageId(Integer.parseInt(lang));
        book.setPages(pags);
        book.setDescription(desc);
        book.setAvailable(Integer.parseInt(disp));

        try {
            DAOBooks dao = new DAOBooksImpl();

            if (!isEdition) {
                dao.registrar(book);
            } else {
                dao.modificar(book);
            }

            String successMsg = isEdition ? "modificado" : "registrado";

            javax.swing.JOptionPane.showMessageDialog(this, "Libro " + successMsg + " exitosamente.\n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);

            if (!isEdition) {
                titleTxt.setText("");
                dateTxt.setText("");
                authorTxt.setText("");
                catTxt.setText("");
                edTxt.setText("");
                langTxt.setText("");
                pagsTxt.setText("");
                descTxt.setText("");
                dispTxt.setText("");
                isbnTxt.setText("");
            }
        } catch (Exception e) {
            String errorMsg = isEdition ? "modificar" : "registrar";
            javax.swing.JOptionPane.showMessageDialog(this, "Ocurrió un error al " + errorMsg + " el libro. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            System.out.println(e.getMessage());
        }
        
    }//GEN-LAST:event_buttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel authorLbl;
    private javax.swing.JTextField authorTxt;
    private javax.swing.JPanel bg;
    private javax.swing.JButton button;
    private javax.swing.JLabel catLbl;
    private javax.swing.JTextField catTxt;
    private javax.swing.JLabel dateLbl;
    private javax.swing.JTextField dateTxt;
    private javax.swing.JLabel descLbl;
    private javax.swing.JTextField descTxt;
    private javax.swing.JLabel dispLbl;
    private javax.swing.JTextField dispTxt;
    private javax.swing.JLabel edLbl;
    private javax.swing.JTextField edTxt;
    private javax.swing.JTextField isbnTxt;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel langLbl;
    private javax.swing.JTextField langTxt;
    private javax.swing.JLabel pagsLbl;
    private javax.swing.JTextField pagsTxt;
    private javax.swing.JLabel title;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JLabel titleLbl1;
    private javax.swing.JTextField titleTxt;
    // End of variables declaration//GEN-END:variables
}
