/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package payments;
import com.mycompany.models.Books;
import com.mycompany.models.Lendings;
import com.mycompany.models.Users;
import com.mycompany.utils.Utils;

import javax.swing.*;

import com.mycompany.ilib.DAOBooksImpl;
import com.mycompany.ilib.DAOLendingsImpl;
import com.mycompany.ilib.DAOUsersImpl;
import com.mycompany.interfaces.DAOBooks;
import com.mycompany.interfaces.DAOLendings;
import com.mycompany.interfaces.DAOUsers;
import com.mycompany.utils.Utils;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author stuart
 */
public class report extends JFrame {
    

    /**
     * Creates new form report
     */

    public static boolean  flag = false;

    public report() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    
    public static boolean pagar(Lendings currentLending) throws Exception{

        
        
        
//        JOptionPane.showMessageDialog(null, "book id" +currentLending.getBook_id());
//        JOptionPane.showMessageDialog(null, "fecha limite " +currentLending.getDate_limit());
//        JOptionPane.showMessageDialog(null, "fecha salida " +currentLending.getDate_out());
//        JOptionPane.showMessageDialog(null, "user id " +currentLending.getUser_id());
//        JOptionPane.showMessageDialog(null, "id " +currentLending.getId());

    

    DAOUsers daoUsers = new DAOUsersImpl();
    Users currentUser = daoUsers.getUserById(currentLending.getUser_id());
    DAOBooks daoBooks = new DAOBooksImpl();
    Books currentBook = daoBooks.getBookById(currentLending.getBook_id());
    DAOLendings daoLendings = new DAOLendingsImpl();
    currentLending = daoLendings.getLending(currentUser, currentBook);

    nombreUsuario.setText(currentUser.getName());


//    if(flag){
        
//        currentLending.setDate_return(Utils.getFechaActual());
//        daoLendings.modificar(currentLending);
//
//        currentBook.setAvailable(currentBook.getAvailable() + 1);
//        daoBooks.modificar(currentBook);
//        
//         JOptionPane.showMessageDialog(null, "libro devuelto");

//    }
        return true;


    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nombreUsuario = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        buttonPagar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        nombreUsuario.setText(" El usuario");

        jLabel2.setText("fsafd");

        buttonPagar.setText("Pagar");
        buttonPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPagarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(nombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(358, Short.MAX_VALUE)
                .addComponent(buttonPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(357, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 302, Short.MAX_VALUE)
                .addComponent(buttonPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonPagarActionPerformed(ActionEvent evt) {//GEN-FIRST:event_buttonPagarActionPerformed
        // TODO add your handling code here:

        flag = true;
    }//GEN-LAST:event_buttonPagarActionPerformed


    public static boolean main(Lendings currentLending) throws Exception {
     
    
        pagar(currentLending);
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                new report().setVisible(true);
            }
        });

        while(!flag){
            return pagar(currentLending);
        }
        
        return false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton buttonPagar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel nombreUsuario;
    // End of variables declaration//GEN-END:variables
}
